services:

    revuelto.embanet.softwareshinobi.digital:

        container_name: revuelto.embanet.softwareshinobi.digital

        image: softwareshinobi/revuelto.embanet.softwareshinobi.digital

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 8000:80

        environment:

            VIRTUAL_HOST: embanet.softwareshinobi.digital

            LETSENCRYPT_HOST: embanet.softwareshinobi.digital
